apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-health
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-health
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-health
    spec:
      serviceAccountName: MAKEFILE_SERVICE_NAME-serviceaccount
      containers:
      - name: MAKEFILE_SERVICE_NAME-health
        imagePullPolicy: Never
        image: MAKEFILE_SERVICE_NAME/pods-api:MAKEFILE_TAG
        command: ["python3","-u","/home/tapis/service/health.py"]
        resources:
          requests:
            cpu: "1"
            memory: "1G"
          limits:
            cpu: "3"
            memory: "3G"
        env:
        - name: api
          value: api
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: service-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: postgres-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: rabbitmq-password
        volumeMounts:
        - name: MAKEFILE_SERVICE_NAME-config
          mountPath: /home/tapis/config.json
          subPath: config.json
#DEV        - name: dev-service
#DEV          mountPath: /home/tapis/service
      volumes:
      - name: MAKEFILE_SERVICE_NAME-config
        configMap: 
          name: MAKEFILE_SERVICE_NAME-config 
#DEV      - name: dev-service
#DEV        hostPath:
#DEV          path: /pods_service/service #NOTE FOR MINIKUBE: Minikube is a vm, you have to minikube mount for hostpath to work
#DEV          type: Directory
