apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-postgres
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-postgres
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-postgres
    spec:
      containers:
      - name: MAKEFILE_SERVICE_NAME-postgres
        image: timescale/timescaledb:latest-pg14
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            apk add openssl
            mkdir -p /tmp/ssl/certs /tmp/ssl/private
            if [ ! -f /tmp/ssl/certs/ssl-cert-snakeoil.pem ] || [ ! -f /tmp/ssl/private/ssl-cert-snakeoil.key ]; then
              openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout /tmp/ssl/private/ssl-cert-snakeoil.key \
                -out /tmp/ssl/certs/ssl-cert-snakeoil.pem \
                -subj "/CN=localhost";
              id
              echo "bing"
              chmod 600 /tmp/ssl/private/ssl-cert-snakeoil.key;
              chown postgres:postgres /tmp/ssl/private/ssl-cert-snakeoil.key
            fi
            docker-entrypoint.sh "$@"
        args: [
          "postgres",
          "-c", "ssl=on",
          "-c", "ssl_cert_file=/tmp/ssl/certs/ssl-cert-snakeoil.pem",
          "-c", "ssl_key_file=/tmp/ssl/private/ssl-cert-snakeoil.key",
          "-c", "max_connections=500"
        ]
        resources:
          requests:
            cpu: ".4"
            memory: ".4G"
          limits:
            cpu: "3"
            memory: "3G"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: pods-admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: postgres-password
        - name: PGSSLMODE
          value: "disable"
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: pods-postgres-vol
          mountPath: "/pgdata"
      volumes:
      - name: pods-postgres-vol
        persistentVolumeClaim:
          claimName: pods-postgres-vol