import re
from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import validator, model_validator, create_model
from codes import PermissionLevel

from tapisservice.tapisfastapi.utils import g
from tapisservice.logs import get_logger
logger = get_logger(__name__)

from __init__ import t
from sqlalchemy.dialects.postgresql import ARRAY
from sqlmodel import Field, select, JSON, Column, String
from models_base import TapisModel, TapisApiModel
from tapis_auth_utils import (
    validate_tapis_auth_response_headers,
    validate_tapis_auth_return_path,
    validate_tapis_auth_allowed_users,
    validate_tapis_auth_excluded_paths,
    validate_tapis_auth_excluded_path_regex,
)


class RouteBase(TapisApiModel):
    # Required
    route_id: str = Field(..., description="Unique route identifier — becomes the public hostname: <route_id>.pods.<tenant-domain>.", primary_key=True)
    port: int = Field(..., description="Backend port the published service listens on.")
    # Optional user-settable config
    backend_host: str = Field("", description="Host/IP traefik dials for this route (an address reachable FROM central — e.g. a tailnet IP/name, or host.minikube.internal in dev). v0: explicit; later prefilled from the node's checkin address.")
    description: str = Field("", description="Description of the route.")
    # tapis_auth — the FULL per-route auth config, same field set as pod networking.
    # Groups in tapis_auth_allowed_users resolve against the ROUTE's permissions list.
    tapis_auth: bool = Field(False, description="If true, will require Tapis auth to access the route.")
    tapis_auth_response_headers: Dict[str, str] = Field({}, description="Specification of headers to forward to the backend when using Tapis auth.", sa_column=Column(JSON))
    tapis_auth_allowed_users: List[str] = Field(["AUTHORIZED_USERS"], description="List of users allowed to access the route when using Tapis auth. Supports literal usernames, '*' (all users), and permission-based groups: 'AUTHORIZED_READS' (READ+), 'AUTHORIZED_USERS' (USER+), 'AUTHORIZED_ADMINS' (ADMIN+, includes APPROVEDADMIN). Groups resolve against the route's permissions list.", sa_column=Column(ARRAY(String)))
    tapis_auth_return_path: str = Field("/", description="Path to redirect to after authenticating via Tapis auth.")
    tapis_auth_excluded_paths: List[str] = Field([], description="List of PathPrefix patterns to exclude from Tapis auth (no forwardAuth). ex. ['/assets', '/static']", sa_column=Column(ARRAY(String)))
    tapis_auth_excluded_path_regex: List[str] = Field([], description="List of PathRegexp patterns to exclude from Tapis auth. ex. ['\\\\.(js|css|ico|png)$']", sa_column=Column(ARRAY(String)))


class RouteBaseRead(RouteBase):
    # Provided
    node_id: str = Field("", description="Node this route publishes from. Set from the request path.", sa_column=Column(String, nullable=False, index=True))
    url: str = Field("", description="Public URL host for this route. Generated by service.")
    creation_ts: datetime | None = Field(None, description="Time (UTC) that this route was created.")
    update_ts: datetime | None = Field(None, description="Time (UTC) that this route was updated.")


class RouteBaseFull(RouteBaseRead):
    # Provided
    tenant_id: str = Field("", description="Tapis tenant used during creation of this route.")
    site_id: str = Field("", description="Tapis site used during creation of this route.")
    permissions: List[str] = Field([], description="Route permissions for each user.", sa_column=Column(ARRAY(String, dimensions=1)))
    action_logs: List[str] = Field([], description="Log of past actions taken on this route.", sa_column=Column(ARRAY(String, dimensions=1)))

    def traefik_service_name(self):
        """Key/name for this route in the rendered traefik dynamic config (and the OAuth
        client id suffix). 'noderoute' segment keeps it disjoint from pod k8_names
        (pods-<site>-<tenant>-<pod_id>[-<net_name>])."""
        return f"pods-{self.site_id}-{self.tenant_id}-noderoute-{self.route_id}"

    def display(self):
        display = self.dict()
        display.pop('action_logs', None)
        display.pop('tenant_id', None)
        display.pop('site_id', None)
        display.pop('permissions', None)
        return display


TapisRouteBaseFull = create_model("TapisRouteBaseFull", __base__=type("_ComboModel", (RouteBaseFull, TapisModel), {}))


class Route(TapisRouteBaseFull, table=True, validate=True):
    @validator('route_id')
    def check_route_id(cls, v):
        reserved_route_ids = ["default", "admin", "system", "central", "pods", "www"]
        if v in reserved_route_ids:
            raise ValueError(f"route_id overlaps with reserved route ids: {reserved_route_ids}")
        res = re.fullmatch(r'[a-z][a-z0-9\-]+', v)
        if not res:
            raise ValueError(f"route_id must be lowercase alphanumeric or hyphen, starting with alpha (it becomes a public hostname).")
        if len(v) > 64 or len(v) < 3:
            raise ValueError(f"route_id length must be between 3-64 characters. Inputted length: {len(v)}")
        return v

    @validator('port')
    def check_port(cls, v):
        if v < 1 or v > 65535:
            raise ValueError(f"port must be between 1 and 65535. Got port: {v}")
        return v

    @validator('backend_host')
    def check_backend_host(cls, v):
        if v:
            if not re.fullmatch(r'[a-z0-9][a-z0-9.\-]*', v):
                raise ValueError(f"backend_host must be a bare hostname or IPv4 address (lowercase alphanumeric, dots, hyphens) — no scheme, port, or path. Got: {v}")
            if len(v) > 253:
                raise ValueError(f"backend_host length must be below 253 characters. Got length: {len(v)}")
        return v

    @validator('description')
    def check_description(cls, v):
        if not v.isascii():
            raise ValueError(f"description field may only contain ASCII characters.")
        if len(v) > 255:
            raise ValueError(f"description field must be less than 255 characters. Inputted length: {len(v)}")
        return v

    # tapis_auth field validation shared with pod networking — see tapis_auth_utils.
    @validator('tapis_auth_response_headers')
    def check_tapis_auth_response_headers(cls, v):
        return validate_tapis_auth_response_headers(v, prefix="route")

    @validator('tapis_auth_return_path')
    def check_tapis_auth_return_path(cls, v):
        return validate_tapis_auth_return_path(v, prefix="route")

    @validator('tapis_auth_allowed_users')
    def check_tapis_auth_allowed_users(cls, v):
        return validate_tapis_auth_allowed_users(v, prefix="route")

    @validator('tapis_auth_excluded_paths')
    def check_tapis_auth_excluded_paths(cls, v):
        return validate_tapis_auth_excluded_paths(v, prefix="route")

    @validator('tapis_auth_excluded_path_regex')
    def check_tapis_auth_excluded_path_regex(cls, v):
        return validate_tapis_auth_excluded_path_regex(v, prefix="route")

    @validator('tenant_id')
    def check_tenant_id(cls, v):
        return g.request_tenant_id

    @validator('site_id')
    def check_site_id(cls, v):
        return g.site_id

    @validator('creation_ts')
    def check_creation_ts(cls, v):
        return datetime.utcnow()

    @validator('update_ts')
    def check_update_ts(cls, v):
        return datetime.utcnow()

    @validator('action_logs')
    def check_action_logs(cls, v):
        return [f"{datetime.utcnow().strftime('%y/%m/%d %H:%M')}: Route object created by '{g.username}'"]

    @validator('permissions')
    def check_permissions(cls, v):
        if not v:
            v = [f"{g.username}:ADMIN"]
        return v

    @model_validator(mode="after")
    def set_url(cls, values):
        # url: <route_id>.pods.<tenant-domain> — same shape as pod networking urls, so
        # the traefik template + auth-url derivation treat both identically.
        # NOTE: Pydantic loops during validation; tenant_id can be unset early on.
        tenant_id = getattr(values, 'tenant_id', None)
        route_id = getattr(values, 'route_id', None)
        if not tenant_id or not route_id:
            return values
        base_url = t.tenant_cache.get_tenant_config(tenant_id=tenant_id).base_url
        object.__setattr__(values, "url", base_url.replace("https://", f"{route_id}.pods."))
        return values

    def log_action(self, msg: str):
        """Append a timestamped entry to action_logs (db_update only auto-logs for pods)."""
        self.action_logs = (self.action_logs or []) + [f"{datetime.utcnow().strftime('%y/%m/%d %H:%M')}: {msg}"]

    @classmethod
    def db_get_for_node(cls, node_id: str, tenant: str = None, site: str = None):
        """All routes belonging to one node."""
        site, tenant, store = cls.get_site_tenant_session(tenant=tenant, site=site)
        stmt = select(Route).where(Route.node_id == node_id)
        return store.run("execute", stmt, scalars=True, all=True)


class NewRoute(RouteBase):
    """
    Object with fields that users are allowed to specify for the Route class.
    """
    pass


# ---------------------------------------------------------------------------
# Probe — central-side reachability test for a route (the UI can't test routes
# itself: TapisUI is external and route hostnames don't resolve in dev)
# ---------------------------------------------------------------------------

class RouteProbeCheck(TapisApiModel):
    ok: bool = Field(..., description="True when an HTTP response came back (any status). False = could not connect.")
    status_code: Optional[int] = Field(None, description="HTTP status returned, when ok.")
    latency_ms: Optional[int] = Field(None, description="Round-trip time in milliseconds, when ok.")
    error: Optional[str] = Field(None, description="Connection error string, when not ok.")
    snippet: Optional[str] = Field(None, description="First bytes of the response body (sanitized), when ok.")


class RouteProbeResult(TapisApiModel):
    route_id: str
    url: str = Field(..., description="Public hostname for the route.")
    tapis_auth: bool = Field(..., description="Whether the route is auth-gated (a 302 on via_proxy then means the auth gate is working).")
    direct: RouteProbeCheck = Field(..., description="Central dialing backend_host:port directly — is the backend itself up?")
    via_proxy: RouteProbeCheck = Field(..., description="Central dialing traefik with the route's public Host header — is the full public path rendered and routing?")


# ---------------------------------------------------------------------------
# Response envelopes
# ---------------------------------------------------------------------------

class RouteResponseModel(RouteBaseRead):
    pass


class RouteProbeResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: RouteProbeResult
    status: str
    version: str


class RouteResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: RouteResponseModel
    status: str
    version: str


class RoutesResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: List[RouteResponseModel]
    status: str
    version: str


class RouteDeleteResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: str
    status: str
    version: str
