from asyncio import protocols
import http
import re
from sre_constants import ANY
from string import ascii_letters, digits
from secrets import choice
from datetime import datetime
from typing import List, Dict, Literal, Any, Set, Optional, Union
from wsgiref import validate
from pydantic import BaseModel, Field, validator, model_validator, create_model
from codes import PERMISSION_LEVELS, PermissionLevel

from tapisservice.tapisfastapi.utils import g
from tapisservice.config import conf
from tapisservice.logs import get_logger
logger = get_logger(__name__)

from __init__ import t

from sqlalchemy import UniqueConstraint
from sqlalchemy.orm import defer
from sqlalchemy.inspection import inspect
from sqlalchemy.dialects.postgresql import ARRAY
from sqlmodel import Field, Session, SQLModel, select, JSON, Column, String
from models_images import Image

# Import VolumeMount and related from centralized utils module
from models_volume_mounts_utils import (
    VolumeMount, 
    MAX_CONFIG_CONTENT_SIZE, 
    VALID_VOLUME_MOUNT_TYPES,
    validate_volume_mounts_dict as _validate_volume_mounts_dict,
    validate_and_convert_volume_mounts,
    interpolate_config_content
)
from models_templates import Template
from models_templates_tags import TemplateTag, derive_template_info
from models_base import TapisModel, TapisApiModel
from models_misc import PermissionsModel, CredentialsModel, LogsModel
from models_volumes import Volume
from models_snapshots import Snapshot

def get_queue_by_name(compute_queues, queue_name):
    logger.debug("top of models_pods.get_queue_by_name().")

    for queue in compute_queues:
        if queue['queue_name'] == queue_name:
            return queue
    return None


class Password(TapisModel, table=True, validate=True):
    # Required
    pod_id: str = Field(..., description = "Name of this pod.", primary_key = True)
    # Provided
    admin_username: str = Field("podsservice", description = "Admin username for pod.")
    admin_password: str = Field("", description = "Admin password for pod.")
    user_username: str = Field("", description = "User username for pod.")
    user_password: str = Field("", description = "User password for pod.")
    # Provided
    tenant_id: str = Field("", description = "Tapis tenant used during creation of this password's pod.")
    site_id: str = Field("", description = "Tapis site used during creation of this password's pod.")

    @validator('tenant_id')
    def check_tenant_id(cls, v):
        logger.debug(f"top of models_pods.Password.check_tenant_id() {g.request_tenant_id}")
        return g.request_tenant_id

    @validator('site_id')
    def check_site_id(cls, v):
        logger.debug(f"top of models_pods.Password.check_site_id() {g.site_id}")
        return g.site_id

    @validator('admin_password')
    def add_admin_password(cls, v):
        password = ''.join(choice(ascii_letters + digits) for i in range(30))
        return password

    @validator('user_password')
    def add_user_password(cls, v):
        password = ''.join(choice(ascii_letters + digits) for i in range(30))
        return password

    @model_validator(mode="after")
    def set_user_username(cls, values):
        object.__setattr__(values, "user_username", getattr(values, "pod_id"))
        return values


class Networking(TapisModel):
    ## Really just https://doc.traefik.io/traefik/middlewares
    protocol: str =  Field("http", description = "Which network protocol to use. `http`, `tcp`, `postgres`, or `local_only`. `local_only` is only accessible from within the cluster.")
    port: int = Field(5000, description = "Pod port to expose via networking.url in this networking object.")
    url: str = Field("", description = "URL used to access the port of the pod defined in this networking object. Generated by service.")
    ip_allow_list: list[str] = Field([], description = "List of IPs that are allowed to access this specific pod port. If empty, all IPs are allowed. ex. ['127.0.0.1/32', '192.168.1.7']")
    tapis_auth: bool = Field(False, description = "If true, will require Tapis auth to access the pod.")
    tapis_auth_response_headers: Dict[str, str] = Field({}, description = "Specification of headers to forward to the pod when using Tapis auth.")
    tapis_auth_allowed_users: list[str] = Field(["AUTHORIZED_USERS"], description = "List of users allowed to access the pod when using Tapis auth. Supports literal usernames, '*' (all users), and permission-based groups: 'AUTHORIZED_READS' (READ+), 'AUTHORIZED_USERS' (USER+), 'AUTHORIZED_ADMINS' (ADMIN+, includes APPROVEDADMIN). Groups resolve against the pod's permissions list.")
    tapis_auth_return_path: str = Field("/", description = "Path to redirect to when accessing the pod via Tapis auth.")
    tapis_auth_excluded_paths: list[str] = Field([], description = "List of PathPrefix patterns to exclude from Tapis auth (no forwardAuth). Useful for static assets that don't need auth. ex. ['/assets', '/static', '/_app']")
    tapis_auth_excluded_path_regex: list[str] = Field([], description = "List of PathRegexp patterns to exclude from Tapis auth. ex. ['\\\\.(js|css|ico|png|jpg|jpeg|webp|gif|svg|woff2?|ttf|map)$']")
    cors_allow_origins: list[str] = Field([], description = "List of CORS allowed origins. ex. ['https://tacc.develop.tapis.io', 'https://tacc.tapis.io']")
    cors_allow_methods: list[str] = Field([], description = "List of CORS allowed methods. ex. ['GET', 'POST', 'PUT', 'DELETE']")
    cors_allow_headers: list[str] = Field([], description = "List of CORS allowed headers. ex. ['Content-Type', 'X-Tapis-Token']")
    cors_allow_credentials: bool = Field(False, description = "Boolean to allow credentials to be sent with CORS requests.")
    cors_max_age: int = Field(100, description = "Max age of CORS preflight requests in seconds.")
    tapis_ui_uri: str = Field("", description = "Path to redirect to when accessing the pod via Tapis UI.")
    tapis_ui_uri_redirect: bool = Field(False, description = "If true, will redirect to the tapis_ui_uri when accessing the pod via Tapis UI. Otherwise, just read-only uri.")
    tapis_ui_uri_description: str = Field("", description = "Describing where the tapis_ui_uri will redirect to.")
    # Proxy compression (Traefik compress middleware)
    proxy_compression: bool = Field(True, description = "Enable Traefik compress middleware for this HTTP endpoint. Enabled by default for all HTTP protocol endpoints.")
    proxy_compression_encodings: list[str] = Field(["zstd", "br", "gzip"], description = "Ordered list of compression encodings by priority. Valid values: 'zstd', 'br', 'gzip'.")
    proxy_compression_excluded_content_types: list[str] = Field([], description = "Content types to exclude from compression. Already-compressed formats (images, video, archives) are excluded automatically. Set explicit types here to add additional exclusions.")
    proxy_compression_min_response_body_bytes: int = Field(1024, description = "Minimum response body size in bytes before compression is applied. Responses smaller than this are not compressed.")

    @validator('protocol')
    def check_protocol(cls, v):
        v = v.lower()
        valid_protocols = ['http', 'tcp', 'postgres', 'local_only']
        if v not in valid_protocols:
            raise ValueError(f"networking.protocol must be one of the following: {valid_protocols}.")
        return v

    @validator('port')
    def check_port(cls, v):
        if 10 > v  or v > 99999:
            raise ValueError(f"networking.port must have 2 to 5 digits. Got port: {v}")
        return v

    @validator('url')
    def check_url(cls, v):
        if v:
            # Regex match to ensure url is safe with only [A-z0-9.-] chars.
            res = re.fullmatch(r'[a-z][a-z0-9.-]+', v)
            if not res:
                raise ValueError(f"networking.url can only contain lowercase alphanumeric characters, periods, and hyphens. Got {v}")
            # pod_id char limit = 64
            if len(v) > 128:
                raise ValueError(f"networking.*.url length must be below 128 characters. Inputted length: {len(v)}")
        return v
    
    @validator('tapis_auth_response_headers')
    def check_tapis_auth_response_headers(cls, v):
        if v:
            if not isinstance(v, dict):
                raise TypeError(f"networking.tapis_auth_response_headers must be dict. Got '{type(v).__name__}'.")
            for header_name, header_val in v.items():
                if not isinstance(header_name, str):
                    raise TypeError(f"networking.tapis_auth_response_headers key type must be str. Got '{type(header_name).__name__}', key: '{header_name}'.")
                if not isinstance(header_val, str):
                    raise TypeError(f"networking.tapis_auth_response_headers val type must be str. Got '{type(header_val).__name__}', value: '{header_val}'.")
        return v
    
    @validator('tapis_auth_return_path')
    def check_tapis_auth_return_path(cls, v):
        if v:
            if not v.startswith('/'):
                raise ValueError(f"networking.tapis_auth_return_path should start with '/'. Got {v}")
            # Regex match to ensure url is safe with only [A-z0-9.-/] chars.
            res = re.fullmatch(r'(?:[A-Za-z0-9.\-_\/]+)', v)
            if not res:
                raise ValueError(f"networking.tapis_auth_return_path should start with '/' and can contain alphanumeric characters, periods, forward-slash, underscores, and hyphens. Got {v}")
            if len(v) > 180:
                raise ValueError(f"networking.tapis_auth_return_path length must be below 180 characters. Got length: {len(v)}")
        return v

    @validator('tapis_auth_allowed_users')
    def check_tapis_auth_allowed_users(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.apis_auth_allowed_users must be list. Got '{type(v).__name__}'.")
            for user in v:
                if not isinstance(user, str):
                    raise TypeError(f"networking.tapis_auth_allowed_users must be list of str. Got '{type(user).__name__}'.")
        return v

    @validator('tapis_auth_excluded_paths')
    def check_tapis_auth_excluded_paths(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.tapis_auth_excluded_paths must be list. Got '{type(v).__name__}'.")
            if len(v) > 50:
                raise ValueError(f"networking.tapis_auth_excluded_paths must have at most 50 entries. Got {len(v)}.")
            for path in v:
                if not isinstance(path, str):
                    raise TypeError(f"networking.tapis_auth_excluded_paths must be list of str. Got '{type(path).__name__}'.")
                if not path.startswith('/'):
                    raise ValueError(f"networking.tapis_auth_excluded_paths values must start with '/'. Got '{path}'.")
                if not path.isascii():
                    raise ValueError(f"networking.tapis_auth_excluded_paths values must be ASCII. Got '{path}'.")
                if len(path) > 256:
                    raise ValueError(f"networking.tapis_auth_excluded_paths values must be less than 256 characters. Got length {len(path)}.")
        return v

    @validator('tapis_auth_excluded_path_regex')
    def check_tapis_auth_excluded_path_regex(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.tapis_auth_excluded_path_regex must be list. Got '{type(v).__name__}'.")
            if len(v) > 20:
                raise ValueError(f"networking.tapis_auth_excluded_path_regex must have at most 20 entries. Got {len(v)}.")
            for pattern in v:
                if not isinstance(pattern, str):
                    raise TypeError(f"networking.tapis_auth_excluded_path_regex must be list of str. Got '{type(pattern).__name__}'.")
                if not pattern.isascii():
                    raise ValueError(f"networking.tapis_auth_excluded_path_regex values must be ASCII. Got '{pattern}'.")
                if len(pattern) > 512:
                    raise ValueError(f"networking.tapis_auth_excluded_path_regex values must be less than 512 characters. Got length {len(pattern)}.")
                # Validate the regex compiles
                try:
                    import re as _re
                    _re.compile(pattern)
                except _re.error as e:
                    raise ValueError(f"networking.tapis_auth_excluded_path_regex contains invalid regex '{pattern}': {e}")
        return v

    @validator('tapis_ui_uri')
    def check_tapis_ui_uri(cls, v):
        if v:
            # must start with /
            if not v.startswith('/'):
                raise ValueError(f"networking.tapis_ui_uri must start with '/'. Got {v}")
            # Regex match to ensure url is safe with only [A-z0-9.-/] chars.
            res = re.fullmatch(r'[\/]+[a-z][a-z0-9.\-\/]+', v)
            if not res:
                raise ValueError(f"networking.tapis_ui_uri can only contain lowercase alphanumeric characters, periods, forward-slash, and hyphens. Must begin with /. Got {v}")
            # pod_id char limit = 64
            if len(v) > 128:
                raise ValueError(f"networking.tapis_ui_uri length must be below 128 characters. Inputted length: {len(v)}")
        return v
    
    @validator('tapis_ui_uri_description')
    def check_tapis_ui_uri_description(cls, v):
        # ensure tapis_ui_uri_description is all ascii
        if not v.isascii():
            raise ValueError(f"networking.tapis_ui_uri_description field may only contain ASCII characters. Got {v}")
        # make sure tapis_ui_uri_description < 255 characters
        if len(v) > 255:
            raise ValueError(f"networking.tapis_ui_uri_description field must be less than 255 characters. Inputted length: {len(v)}")
        return v

    # create validators for the 5 cors fields
    @validator('cors_allow_origins')
    def check_cors_allow_origins(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.cors_allow_origins must be list. Got '{type(v).__name__}'.")
            for origin in v:
                if not isinstance(origin, str):
                    raise TypeError(f"networking.cors_allow_origins must be list of str. Got '{type(origin).__name__}'.")
        return v
    
    @validator('cors_allow_methods')
    def check_cors_allow_methods(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.cors_allow_methods must be list. Got '{type(v).__name__}'.")
            for method in v:
                if not isinstance(method, str):
                    raise TypeError(f"networking.cors_allow_methods must be list of str. Got '{type(method).__name__}'.")
        return v

    @validator('cors_allow_headers')
    def check_cors_allow_headers(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.cors_allow_headers must be list. Got '{type(v).__name__}'.")
            for header in v:
                if not isinstance(header, str):
                    raise TypeError(f"networking.cors_allow_headers must be list of str. Got '{type(header).__name__}'.")
        return v

    @validator('cors_allow_credentials')
    def check_cors_allow_credentials(cls, v):
        if v:
            if not isinstance(v, bool):
                raise TypeError(f"networking.cors_allow_credentials must be bool. Got '{type(v).__name__}'.")
        return v

    @validator('cors_max_age')
    def check_cors_max_age(cls, v):
        if v:
            if not isinstance(v, int):
                raise TypeError(f"networking.cors_max_age must be int. Got '{type(v).__name__}'.")
            if v < 0:
                raise ValueError(f"networking.cors_max_age must be greater than 0. Got {v}")
            # max is 100s
            if v > 100:
                raise ValueError(f"networking.cors_max_age must be less than 3600 seconds. Got {v}")
        return v

    @validator('ip_allow_list')
    def check_ip_allow_list(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.ip_allow_list must be list. Got '{type(v).__name__}'.")
            for ip in v:
                if not isinstance(ip, str):
                    raise TypeError(f"networking.ip_allow_list must be list of str. Got '{type(ip).__name__}'.")
                ## ensure ip 123.232.323/xx. Return error if * is str as that's not allowed.
                if ip == "*":
                    raise ValueError(f"networking.ip_allow_list cannot contain '*'. All values must be valid IPs or CIDR ranges.")
                # Regex match to ensure ip is safe with only [0-9./] chars.
                res = re.fullmatch(r'(\d{1,3}\.){3}\d{1,3}(/\d{1,2})?', ip)
                if not res:
                    raise ValueError(f"networking.ip_allow_list can only contain valid IPs or CIDR ranges. Got {ip}")
        return v

    @validator('proxy_compression_encodings')
    def check_proxy_compression_encodings(cls, v):
        valid_encodings = ['zstd', 'br', 'gzip']
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.proxy_compression_encodings must be list. Got '{type(v).__name__}'.")
            for enc in v:
                if not isinstance(enc, str):
                    raise TypeError(f"networking.proxy_compression_encodings must be list of str. Got '{type(enc).__name__}'.")
                if enc not in valid_encodings:
                    raise ValueError(f"networking.proxy_compression_encodings values must be one of {valid_encodings}. Got '{enc}'.")
            if len(v) == 0:
                raise ValueError(f"networking.proxy_compression_encodings must have at least one encoding when proxy_compression is enabled.")
            # Check for duplicates
            if len(v) != len(set(v)):
                raise ValueError(f"networking.proxy_compression_encodings must not contain duplicates. Got {v}.")
        return v

    @validator('proxy_compression_excluded_content_types')
    def check_proxy_compression_excluded_content_types(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"networking.proxy_compression_excluded_content_types must be list. Got '{type(v).__name__}'.")
            for ct in v:
                if not isinstance(ct, str):
                    raise TypeError(f"networking.proxy_compression_excluded_content_types must be list of str. Got '{type(ct).__name__}'.")
                if not ct.isascii():
                    raise ValueError(f"networking.proxy_compression_excluded_content_types values must be ASCII. Got '{ct}'.")
                if len(ct) > 128:
                    raise ValueError(f"networking.proxy_compression_excluded_content_types values must be less than 128 characters. Got length {len(ct)}.")
            if len(v) > 50:
                raise ValueError(f"networking.proxy_compression_excluded_content_types must have at most 50 entries. Got {len(v)}.")
        return v

    @validator('proxy_compression_min_response_body_bytes')
    def check_proxy_compression_min_response_body_bytes(cls, v):
        if not isinstance(v, int):
            raise TypeError(f"networking.proxy_compression_min_response_body_bytes must be int. Got '{type(v).__name__}'.")
        if v < 0:
            raise ValueError(f"networking.proxy_compression_min_response_body_bytes must be >= 0. Got {v}.")
        if v > 10485760:  # 10 MiB max
            raise ValueError(f"networking.proxy_compression_min_response_body_bytes must be <= 10485760 (10 MiB). Got {v}.")
        return v

    @model_validator(mode="after")
    def check_tapis_protocol_with_configured_options(cls, values):
        protocol = getattr(values, 'protocol', None)
        tapis_auth = getattr(values, 'tapis_auth', None)
        # cors too are http only
        cors_allow_origins = getattr(values, 'cors_allow_origins', None)
        cors_allow_methods = getattr(values, 'cors_allow_methods', None)
        cors_allow_headers = getattr(values, 'cors_allow_headers', None)
        cors_allow_credentials = getattr(values, 'cors_allow_credentials', None)
        cors_max_age = getattr(values, 'cors_max_age', None)

        if tapis_auth and protocol != "http":
            raise ValueError(f"networking.tapis_auth can only be used with protocol 'http'. Got protocol {protocol}.")

        if cors_allow_origins:
            if protocol != "http":
                raise ValueError(f"networking.cors_* can only be used with protocol 'http'. Got protocol {protocol}.")

        # Silently disable proxy_compression for non-http protocols (don't error, for backwards compat)
        proxy_compression = getattr(values, 'proxy_compression', None)
        if proxy_compression and protocol != "http":
            object.__setattr__(values, 'proxy_compression', False)

        # Silently clear tapis_auth exclusion paths for non-http protocols
        if protocol != "http":
            tapis_auth_excluded_paths = getattr(values, 'tapis_auth_excluded_paths', None)
            tapis_auth_excluded_path_regex = getattr(values, 'tapis_auth_excluded_path_regex', None)
            if tapis_auth_excluded_paths:
                object.__setattr__(values, 'tapis_auth_excluded_paths', [])
            if tapis_auth_excluded_path_regex:
                object.__setattr__(values, 'tapis_auth_excluded_path_regex', [])

        return values

class Resources(TapisModel):
    # CPU/Mem defaults are set in configschema.json
    # CPU
    cpu_request: int = Field(conf.default_pod_cpu_request, description = "CPU allocation pod requests at startup. In millicpus (m). 1000 = 1 cpu.")
    cpu_limit: int = Field(conf.default_pod_cpu_limit, description = "CPU allocation pod is allowed to use. In millicpus (m). 1000 = 1 cpu.")
    # Mem
    mem_request: int = Field(conf.default_pod_mem_request, description = "Memory allocation pod requests at startup. In megabytes (Mi)")
    mem_limit: int = Field(conf.default_pod_mem_limit, description = "Memory allocation pod is allowed to use. In megabytes (Mi)")
    # Ephemeral Storage
    ephemeral_storage_request: int = Field(conf.default_pod_ephemeral_storage_request, description = "Ephemeral storage pod requests at startup. In mebibytes (Mi)")
    ephemeral_storage_limit: int = Field(conf.default_pod_ephemeral_storage_limit, description = "Ephemeral storage pod is allowed to use. In mebibytes (Mi)")
    # GPU
    gpus: int = Field(0, description = "GPU allocation pod is allowed to use. In integers of GPUs. (we only have 1 currently ;) )")

    @validator('cpu_request', 'cpu_limit')
    def check_cpu_resources(cls, v):
        if conf.minimum_pod_cpu_val > v  or v > conf.maximum_pod_cpu_val:
            raise ValueError(
                f"resources.cpu_x out of bounds. Received: {v}. Maximum: {conf.maximum_pod_cpu_val}. Minimum: {conf.minimum_pod_cpu_val}.",
                 " User requires extra role to break bounds. Contact admin."
                )
        return v

    @validator('mem_request', 'mem_limit')
    def check_mem_resources(cls, v):
        if conf.minimum_pod_mem_val > v  or v > conf.maximum_pod_mem_val:
            raise ValueError(
                f"resources.mem_x out of bounds. Received: {v}. Maximum: {conf.maximum_pod_mem_val}. Minimum: {conf.minimum_pod_mem_val}.",
                 " User requires extra role to break bounds. Contact admin."
                )
        return v

    @validator('ephemeral_storage_request', 'ephemeral_storage_limit')
    def check_ephemeral_storage_resources(cls, v):
        # Allow -1 (unlimited) only if the default is also -1 (admin has enabled unlimited)
        if v == -1:
            if conf.default_pod_ephemeral_storage_request == -1 or conf.default_pod_ephemeral_storage_limit == -1:
                return v
            else:
                raise ValueError(
                    f"resources.ephemeral_storage_x: -1 (unlimited) is not allowed. "
                    f"Admin has not enabled unlimited ephemeral storage (defaults are not -1). "
                    f"Use values between {conf.minimum_pod_ephemeral_storage_val} and {conf.maximum_pod_ephemeral_storage_val}."
                )
        if conf.minimum_pod_ephemeral_storage_val > v or v > conf.maximum_pod_ephemeral_storage_val:
            raise ValueError(
                f"resources.ephemeral_storage_x out of bounds. Received: {v}. Maximum: {conf.maximum_pod_ephemeral_storage_val}. Minimum: {conf.minimum_pod_ephemeral_storage_val}. "
                f"User requires extra role to break bounds. Contact admin."
                )
        return v

    @validator('gpus')
    def check_gpus(cls, v):
        if 0 > v  or v > conf.maximum_pod_gpu_val:
            raise ValueError(
                f"resources.gpus out of bounds. Received: {v}. Maximum: {conf.maximum_pod_gpu_val}. Minimum: 0.",
                 " User requires extra role to break bounds. Contact admin."
                )
        return v
    @model_validator(mode="after")
    def ensure_request_lessthan_limit(cls, values):
        cpu_request = getattr(values, 'cpu_request')
        cpu_limit = getattr(values, 'cpu_limit')
        mem_request = getattr(values, 'mem_request')
        mem_limit = getattr(values, 'mem_limit')
        ephemeral_storage_request = getattr(values, 'ephemeral_storage_request')
        ephemeral_storage_limit = getattr(values, 'ephemeral_storage_limit')
        gpus = getattr(values, 'gpus') # There's no request/limit for gpus, just an int validated in check_gpus
        
        # Check cpu values
        if cpu_request and cpu_limit and cpu_request > cpu_limit:
            raise ValueError(f"resources.cpu_x found cpu_request({cpu_request}) > cpu_limit({cpu_limit}). Request must be less than or equal to limit.")
        
        # Check mem values
        if mem_request and mem_limit and mem_request > mem_limit:
            raise ValueError(f"resources.mem_x found mem_request({mem_request}) > mem_limit({mem_limit}). Request must be less than or equal to limit.")
        
        # Check ephemeral storage values (skip if either is -1, which means unlimited/unset)
        if ephemeral_storage_request and ephemeral_storage_limit and ephemeral_storage_request != -1 and ephemeral_storage_limit != -1:
            if ephemeral_storage_request > ephemeral_storage_limit:
                raise ValueError(f"resources.ephemeral_storage_x found ephemeral_storage_request({ephemeral_storage_request}) > ephemeral_storage_limit({ephemeral_storage_limit}). Request must be less than or equal to limit. Use -1 for unlimited.")
        
        return values


# Re-export validate_volume_mounts_dict with same signature for backwards compatibility
def validate_volume_mounts_dict(volume_mounts: Dict[str, Any], context: str = "volume_mounts") -> Dict[str, VolumeMount]:
    """
    Validate and convert volume_mounts dict to Dict[str, VolumeMount].
    
    This is a wrapper around the centralized validation function that 
    adds context to error messages.
    """
    if not isinstance(volume_mounts, dict):
        raise TypeError(f"{context} must be a dict keyed by mount_path. Got {type(volume_mounts).__name__}.")
    
    try:
        validated = _validate_volume_mounts_dict(volume_mounts)
    except Exception as e:
        raise ValueError(f"{context}: {str(e)}")
    
    # Convert validated dicts back to VolumeMount objects
    result = {}
    for mount_path, mount_config in validated.items():
        if mount_config is None:
            result[mount_path] = None
        elif isinstance(mount_config, dict):
            result[mount_path] = VolumeMount(**mount_config)
        elif isinstance(mount_config, VolumeMount):
            result[mount_path] = mount_config
        else:
            result[mount_path] = mount_config
    
    return result


class Probes(TapisModel):
    type: str =  Field("", description = "Type of volume to attach.")
    mount_path: str = Field("/tapis_volume_mount", description = "Path to mount volume to.")
    sub_path: str = Field("", description = "Path to mount volume to.")

    @validator('type')
    def check_type(cls, v):
        v = v.lower()
        valid_types = ['tapisvolume', 'tapissnapshot', 'pvc']
        if v not in valid_types:
            raise ValueError(f"volumemount.type must be one of the following: {valid_types}.")
        return v

    @validator('mount_path')
    def check_mount_path(cls, v):
        return v

    @validator('sub_path')
    def check_sub_path(cls, v):
        return v


class PodBase(TapisApiModel):
    # Required
    pod_id: str = Field(..., description = "Name of this pod.", primary_key=True)

    # Optional
    image: str = Field("", description = "Which docker image to use, must be on allowlist, check /pods/images for list.")
    template: str = Field("", description = "Which pod template to use as base of pod fields. User set attributes will overwrite template fields.")
    description: str = Field("", description = "Description of this pod.")
    command: List[str] | None = Field(None, description = 'Command to run in pod. ex. `["sleep", "5000"]` or `["/bin/bash", "-c", "(exec myscript.sh)"]`', sa_column=Column(ARRAY(String)))
    arguments: List[str] | None = Field(None, description = "Arguments for the Pod's command.", sa_column=Column(ARRAY(String)))
    environment_variables: Dict[str, Any] = Field({}, description = "Environment variables to inject into k8 pod. Use `${pods:secrets:KEY}` to reference secret_map entries.", sa_column=Column(JSON))
    secret_map: Dict[str, str] = Field({}, description = "Map of keys to secret values. Syntax: ${secret:name} (user secret), ${secret:user:name} (explicit owner). Reference in environment_variables via ${pods:secrets:KEY}. Resolved at pod start.", sa_column=Column(JSON))
    #probes: Dict[str, Any] = Field({}, description = "Probes to run on pod. ex. `{\"livenessProbe\": {\"httpGet\": {\"path\": \"/\", \"port\": 5000}}}`", sa_column=Column(JSON))
    status_requested: str = Field("ON", description = "Status requested by user, `ON`, `OFF`, or `RESTART`.")
    volume_mounts: Dict[str, Optional[VolumeMount]] = Field(
        {}, 
        description = 'Volume mounts keyed by mount_path. Values are VolumeMount objects (see schema) or null (to remove inherited mount). Ex: {"/data": {"type": "tapisvolume", "source_id": "myvolume"}, "/etc/config.ini": {"type": "ephemeral", "config_content": "key=value"}}',
        sa_column=Column(JSON)
    )
    time_to_stop_default: int = Field(43200, description = "Default time (sec) for pod to run from instance start. -1 for unlimited. 12 hour default.")
    time_to_stop_instance: int | None = Field(None, description = "Time (sec) for pod to run from instance start. Reset each time instance is started. -1 for unlimited. None uses default.")
    networking: Dict[str, Networking] = Field({"default": {"protocol": "http", "port": 5000}}, description = 'Networking information. `{"url_suffix": {"protocol": "http"  "tcp", "port": int}}`', sa_column=Column(JSON))
    resources: Resources = Field({}, description = 'Pod resource management `{"cpu_limit": 3000, "mem_limit": 3000, "cpu_request": 500, "mem_limit": 500, "gpus": 0}`', sa_column=Column(JSON))
    compute_queue: str = Field("default", description = "Queue to run pod in. `default` is the default queue.")
    template_overrides: Dict[str, Any] | None = Field(None, description = 'Partial overrides for template values. Override volume_mounts or secret_map values without rewriting full template field. Ex: {"volume_mounts": {"/data": {"source_id": "my-vol"}}, "secret_map": {"DB_PASS": "${secret:mypass}"}}', sa_column=Column(JSON))

class PodBaseRead(PodBase):
    # Provided
    time_to_stop_ts: datetime | None = Field(None, description = "Time (UTC) that this pod is scheduled to be stopped. Change with time_to_stop_instance.")
    status: str = Field("STOPPED", description = "Current status of pod.")
    status_container: Dict = Field({}, description = "Status of container if exists. Gives phase.", sa_column=Column(JSON))
    creation_ts: datetime | None = Field(None, description = "Time (UTC) that this pod was created.")
    update_ts: datetime | None = Field(None, description = "Time (UTC) that this pod was last updated by a user action.")
    last_status_check_ts: datetime | None = Field(None, description = "Time (UTC) of last automated health/status check.")
    start_instance_ts: datetime | None = Field(None, description = "Time (UTC) that this pod instance was started.")


class PodBaseFull(PodBaseRead):
    # Provided
    tenant_id: str = Field("", description = "Tapis tenant used during creation of this pod.")
    site_id: str = Field("", description = "Tapis site used during creation of this pod.")
    k8_name: str = Field("", description = "Name to use for Kubernetes name.")
    logs: str = Field("", description = "Logs from kubernetes pods, useful for debugging and reading results.")
    permissions: List[str] = Field([], description = "Pod permissions for each user.", sa_column=Column(ARRAY(String, dimensions=1)))
    modified_fields: List[str] = Field([], description = "Fields that have been modified by the user since creation.", sa_column=Column(ARRAY(String, dimensions=1)))
    action_logs: List[str] = Field([], description = "Log of past 10 actions taken on this pod.", sa_column=Column(ARRAY(String, dimensions=1)))
    
    def display(self, include_configs: bool = False):
        """Return displayable dict, optionally including config content.
        
        Args:
            include_configs: If True, include full config_content in ephemeral mounts.
                           If False (default), replace with placeholder to reduce response size.
        """
        display = self.dict()
        display.pop('logs', None)
        display.pop('k8_name')
        display.pop('tenant_id')
        display.pop('permissions')
        display.pop('site_id')
        display.pop('modified_fields')
        display.pop('action_logs')
        
        # Redact config_content if not requested (for both ephemeral and tapisvolume types)
        if not include_configs and display.get('volume_mounts'):
            for mount_path, mount_config in display['volume_mounts'].items():
                if mount_config and mount_config.get('type') in ('ephemeral', 'tapisvolume') and mount_config.get('config_content'):
                    content_size = len(mount_config['config_content'])
                    mount_config['config_content'] = f"<{content_size} bytes - use ?include_configs=true to retrieve>"
        
        return display


TapisPodBaseFull = create_model("TapisPodBaseFull", __base__= type("_ComboModel", (PodBaseFull, TapisModel), {}))


class Pod(TapisPodBaseFull, table=True, validate=True):
    @validator('pod_id')
    def check_pod_id(cls, v):
        # In case we want to add reserved keywords.
        reserved_pod_ids = ["catalog", "snapshots", "volumes", "admin", "catalogs", "snapshot", "volume", "image", "images", "template", "templates"]
        if v in reserved_pod_ids:
            raise ValueError(f"pod_id overlaps with reserved pod ids: {reserved_pod_ids}")
        # Regex match full pod_id to ensure a-z0-9.
        res = re.fullmatch(r'[a-z][a-z0-9]+', v)
        if not res:
            raise ValueError(f"pod_id must be lowercase alphanumeric. First character must be alpha.")
        # pod_id char limit = 64
        if len(v) > 64 or len(v) < 3:
            raise ValueError(f"pod_id length must be between 3-64 characters. Inputted length: {len(v)}")
        return v

    @validator('tenant_id')
    def check_tenant_id(cls, v):
        return g.request_tenant_id

    @validator('site_id')
    def check_site_id(cls, v):
        return g.site_id

    @validator('creation_ts')
    def check_creation_ts(cls, v):
        return datetime.utcnow()
    
    @validator('update_ts')
    def check_update_ts(cls, v):
        return datetime.utcnow()

    @validator('action_logs')
    def check_action_logs(cls, v):
        return [f"{datetime.utcnow().strftime('%y/%m/%d %H:%M')}: Pod object created by '{g.username}'"]

    @validator('permissions')
    def check_permissions(cls, v):
        #By default add author permissions to model.
        if not v:
            v = [f"{g.username}:ADMIN"]
        # Validate each permission entry format
        for perm in v:
            if ':' not in perm:
                raise ValueError(f"Each permission must be in 'user:LEVEL' format. Got '{perm}'.")
            user, level = perm.split(':', 1)
            if not user:
                raise ValueError(f"Permission user/key cannot be empty. Got '{perm}'.")
            if level not in PERMISSION_LEVELS:
                raise ValueError(f"Permission level must be one of {PERMISSION_LEVELS}. Got '{level}' in '{perm}'.")
            # Validate user format: standard username (alphanumeric + _) or tenant.<tenant_id>
            if user.startswith('tenant.'):
                tenant_id = user[len('tenant.'):]
                if not tenant_id:
                    raise ValueError(f"'tenant.' permission must include a tenant ID. Got '{perm}'.")
                res = re.fullmatch(r'[a-z][a-z0-9-]*', tenant_id)
                if not res:
                    raise ValueError(f"'tenant.' permission tenant ID must be lowercase alphanumeric (with hyphens). Got '{tenant_id}'.")
                if level != 'READ':
                    raise ValueError(f"tenant.* permissions only support READ level (cross-tenant auth gate). Got '{level}' in '{perm}'.")
            else:
                # Standard username: alphanumeric with underscores/hyphens/dots/@(for emails)
                res = re.fullmatch(r'[a-zA-Z][a-zA-Z0-9_.@-]*', user)
                if not res:
                    raise ValueError(f"Permission username must start with a letter and may contain alphanumeric characters, underscores, hyphens, dots, or @ (for email addresses). Got '{user}'.")
        return v

    @validator('environment_variables')
    def check_environment_variables(cls, v):
        if v:
            if not isinstance(v, dict):
                raise TypeError(f"environment_variable must be dict. Got {type(v).__name__}.")
            for env_key, env_val in v.items():
                if not isinstance(env_key, str):
                    raise TypeError(f"environment_variable key must be str. Got {type(env_key).__name__}.")
                if not isinstance(env_val, str):
                    raise TypeError(f"environment_variable val must be str. Got {type(env_val).__name__}.")
        return v

    @validator('secret_map')
    def check_secret_map(cls, v):
        """Validate secret_map format for pods.
        
        Pod secret_map can contain:
        - User secrets: ${secret:name} or ${secret:user:name}
        - Literal strings for direct values
        
        Full validation (ownership, existence) happens at pod start time.
        """
        if not v:
            return v
        if not isinstance(v, dict):
            raise TypeError(f"secret_map must be dict. Got {type(v).__name__}.")
        for key, value in v.items():
            if not isinstance(key, str):
                raise TypeError(f"secret_map key must be str. Got {type(key).__name__}.")
            if not isinstance(value, str):
                raise TypeError(f"secret_map value must be str. Got {type(value).__name__}.")
            # Basic format check - key should be alphanumeric with underscores/hyphens
            if not key.replace('_', '').replace('-', '').isalnum():
                raise ValueError(f"secret_map key must be alphanumeric and may include '_' or '-'. Got: {key}")
        return v

    @validator('volume_mounts', pre=True)
    def check_volume_mounts(cls, v):
        """Validate volume_mounts dict structure (keyed by mount_path)."""
        if not v:
            return v
        
        # Use consolidated validation function (handles legacy list format + VolumeMount validation)
        return validate_and_convert_volume_mounts(v, use_full_validation=True)

    @model_validator(mode="after")
    def check_volume_mounts_db(cls, values):
        """Validate that referenced volumes/snapshots exist in database."""
        volume_mounts = getattr(values, 'volume_mounts', None)
        tenant_id = getattr(values, 'tenant_id', None)
        site_id = getattr(values, 'site_id', None)
        
        if volume_mounts and tenant_id and tenant_id != "" and site_id and site_id != "":
            for mount_path, mount_config in volume_mounts.items():
                # Skip null mounts (used to remove template mounts)
                if mount_config is None:
                    continue
                
                # Handle both dict and VolumeMount object
                if isinstance(mount_config, dict):
                    vol_type = mount_config.get('type', '').lower()
                    source_id = mount_config.get('source_id', '')
                else:
                    vol_type = (getattr(mount_config, 'type', '') or '').lower()
                    source_id = getattr(mount_config, 'source_id', '') or ''
                
                if vol_type == "tapisvolume":
                    volume = Volume.db_get_with_pk(source_id, tenant=tenant_id, site=site_id)
                    if not volume:
                        raise ValueError(f"volume_mounts['{mount_path}'] source_id '{source_id}' not found. No volume with this ID exists.")
                
                elif vol_type == "tapissnapshot":
                    snapshot = Snapshot.db_get_with_pk(source_id, tenant=tenant_id, site=site_id)
                    if not snapshot:
                        raise ValueError(f"volume_mounts['{mount_path}'] source_id '{source_id}' not found. No snapshot with this ID exists.")
                
                # 'ephemeral' doesn't need db validation - config is inline
                # 'pvc' type doesn't need db validation - it references k8s PVC
        
        return values
    
    @validator('arguments')
    def check_arguments(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"arguments must be list. Got {type(v).__name__}.")
            for arg in v:
                if not isinstance(arg, str):
                    raise TypeError(f"arguments must be list of str. Got {type(arg).__name__}.")
        return v

    @validator('command')
    def check_command(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"command must be list. Got {type(v).__name__}.")
            for arg in v:
                if not isinstance(arg, str):
                    raise TypeError(f"command must be list of str. Got {type(arg).__name__}.")
        return v

    @validator('modified_fields')
    def check_modified_fields(cls, v):
        if v:
            if not isinstance(v, list):
                raise TypeError(f"modified_fields must be list. Got {type(v).__name__}.")
            for arg in v:
                if not isinstance(arg, str):
                    raise TypeError(f"modified_fields must be list of str. Got {type(arg).__name__}.")
                if arg.startswith("resources."):
                    if arg not in ["resources.cpu_request", "resources.cpu_limit", "resources.mem_request", "resources.mem_limit", "resources.gpus", "resources.ephemeral_storage_request", "resources.ephemeral_storage_limit"]:
                        raise ValueError(f"modified_fields must match the fields of the Pod object. Got {arg}.")
                elif arg not in PodBase.__fields__.keys():
                    raise ValueError(f"modified_fields must match the fields of the Pod object. Got {arg}.")
        return v

    # template
    @validator('template')
    def check_template(cls, v):
        if v:
            if not isinstance(v, str):
                raise TypeError(f"template must be str. Got {type(v).__name__}.")

            # Can't have @ before : in template.
            if "@" in v:
                first_segment, second_segment = v.split("@")
                if not ":" in first_segment:
                    raise ValueError(f"User specified @timestamp without :tag. Template should be formated as 'template_name:template_tag@tag_timestamp'. Got {v}")
        return v

    @model_validator(mode="after")
    def check_template_global(cls, values):
        template = getattr(values, 'template', None)
        tenant_id = getattr(values, 'tenant_id', None)
        site_id = getattr(values, 'site_id', None)

        if template != "" and tenant_id != None and tenant_id != "" and site_id != None and site_id != "":
            logger.debug(f"top of PodBaseFull.check_template() with template: {template}, tenant_id: {tenant_id}, site_id: {site_id}")
            template_name_str, template, template_tag = derive_template_info(template, tenant=tenant_id, site=site_id)
            object.__setattr__(values, "template", template_name_str)
            
        return values

    @model_validator(mode="after")
    def check_approvedadmin_settings(cls, values):
        environment_variables = getattr(values, 'environment_variables', None)
        permissions = getattr(values, 'permissions', None)
        networking = getattr(values, 'networking', None)

        # Check TAPIS_PODS_IMAGEPULLSECRET
        if permissions and environment_variables:
            # Check if TAPIS_PODS_IMAGEPULLSECRET is set
            if "TAPIS_PODS_IMAGEPULLSECRET" in environment_variables:
                image_pull_secret_user = environment_variables.get("TAPIS_PODS_IMAGEPULLSECRET")
                if not isinstance(image_pull_secret_user, str):
                    raise TypeError(f"environment_variables TAPIS_PODS_IMAGEPULLSECRET must be str. Got {type(image_pull_secret_user).__name__}.")

        # Check CORS settings in Networking
        if networking:
            for net_name, net_info in networking.items():
                if not isinstance(net_info, dict):
                    net_info = net_info.dict()
                cors_allow_origins = net_info.get('cors_allow_origins', [])
                cors_allow_methods = net_info.get('cors_allow_methods', [])
                cors_allow_headers = net_info.get('cors_allow_headers', [])
                cors_allow_credentials = net_info.get('cors_allow_credentials', None)
                cors_max_age = net_info.get('cors_max_age', None)
                protocol = net_info.get('protocol')

                # If cors are used.
                if cors_allow_origins and permissions:
                    # Ensure at least one user has APPROVEDADMIN permission
                    approved_admin = any(permission.endswith(":APPROVEDADMIN") for permission in permissions)
                    if not approved_admin:
                        raise ValueError(
                            f"No user has APPROVEDADMIN permission to configure CORS settings for networking object '{net_name}', cors_allow_origins: {cors_allow_origins}. Contact admin for approval."
                        )
        return values

    @model_validator(mode="after") # image and template if image not provided
    def check_image(cls, values):
        image = getattr(values, 'image', None)
        template = getattr(values, 'template', None)
        tenant_id = getattr(values, 'tenant_id', None)
        site_id = getattr(values, 'site_id', None)

        #logger.info(f"top of PodBaseFull.check_image() with image: {image}, template: {template}, tenant_id: {tenant_id}, site_id: {site_id}")
        #logger.debug(f"image type: {type(image).__name__}, template type: {type(template).__name__}, tenant_id type: {type(tenant_id).__name__}, site_id type: {type(site_id).__name__}")
        # pydantic sets None if not validated, and "" for validated strings; we wait until values are not None.
        if image != None and template != None and tenant_id != "" and tenant_id != None and site_id != None and site_id != "":        
            logger.debug("got into image and template check.")
            if image:
                # priority to template.image, so if it's set, it's top
                pass
            elif not image and not template: # check if either are moved from default
                raise ValueError("image is required if template is not provided.")
            elif not image and template:
                logger.debug(f"top of first check_images derive_template_info() with tenant_id: {tenant_id}, site_id: {site_id}")
                template_name_str, template, template_tag = derive_template_info(template, tenant=tenant_id, site=site_id)
                image = template_tag.pod_definition.get("image")
                inner_template = template_tag.pod_definition.get("template")
                if image:
                    pass
                elif not image and not inner_template:
                    raise ValueError("Could not find image or template on template that the user specified.")
                elif not image and inner_template:
                    logger.debug(f"top of second check_images derive_template_info() with tenant_id: {tenant_id}, site_id: {site_id}")
                    #raise ValueError("Pods cannot have more than 2 levels of templates. (template -> template -> image)")
                    template_name_str, template, template_tag = derive_template_info(inner_template, tenant=tenant_id, site=site_id)
                    image = template_tag.pod_definition.get("image")
                    inner_inner_template = template_tag.pod_definition.get("template")
                    if image:
                        pass
                    elif not image and not inner_inner_template:
                        raise ValueError("Could not find image or template on template that the user specified.")
                    elif inner_inner_template:
                        raise ValueError("Pods cannot have more than 2 levels of templates. (template -> template -> image)")
                    ##### TODO THIS SHOULD BE EXPANDED
                # at this point we know image/template initialization is complete as not NONE
    
            # Get rid of tag, we don't check that at all.
            if image.count(":") > 1:
                raise ValueError("image cannot have more than one ':' in the string. Should be used to separate the tag from the image name.")
            if ":" in image:
                image = image.split(":")[0]
            
            # We search the siteadmintable schema for the images that our tenant is allowed to use.
            all_images = Image.db_get_all(tenant="siteadmintable", site=g.site_id)
            custom_allow_list = []
            main_tenants = ["tacc", "icicleai", "icicle", "dev", "astria", "a2cps", "scoped"]
            logger.debug(f"Top of adding images to custom_allow_list. main_tenants: {main_tenants}, tenant_id: {tenant_id}")
            for allowed_image in all_images:
                tenants = allowed_image.tenants
                # If "-<tenant>" is present, restrict access for that tenant
                if f"-{tenant_id}" in tenants:
                    continue
                # "**" allows all tenants
                if "**" in tenants:
                    custom_allow_list.append(allowed_image.image)
                # "*" allows only main_tenants
                elif "*" in tenants and tenant_id in main_tenants:
                    custom_allow_list.append(allowed_image.image)
                # Explicit tenant allow
                elif tenant_id in tenants:
                    custom_allow_list.append(allowed_image.image)
            # Then we add images from the conf.image_allow_list
            custom_allow_list += conf.get('image_allow_list', [])

            logger.debug(f"Bottom of check_image(). image: {image}, custom_allow_list: {custom_allow_list}")
            if image not in custom_allow_list:
                raise ValueError(f"Custom pod.image images must be in allowlist. View available images at /pods/images or contact admin via github issue or slack (cgarcia). Image derived: {image}")

        return values


    @validator('time_to_stop_default')
    def check_time_to_stop_default(cls, v):
        if v != -1 and v < 300:
            raise ValueError(f"Pod time_to_stop_default must be -1 or be greater than 300 seconds.")
        return v

    @validator('time_to_stop_instance')
    def check_time_to_stop_instance(cls, v):
        if v and v != -1 and v < 300:
            raise ValueError(f"Pod time_to_stop_instance must be -1 or be greater than 300 seconds.")
        return v

    @validator('description')
    def check_description(cls, v):
        # ensure description is all ascii
        if not v.isascii():
            raise ValueError(f"description field may only contain ASCII characters.")            
        # make sure description < 255 characters
        if len(v) > 255:
            raise ValueError(f"description field must be less than 255 characters. Inputted length: {len(v)}")
        return v

    @validator('networking')
    def check_networking(cls, v):
        if v:
            # Only allow 3 url:port pairs per pod. Trying to keep services minimal.
            # I have uses for 2 ports, not 3, but might as well keep it available.
            if len(v) > 4:
                raise ValueError(f"networking dictionary may only contain up to 4 stanzas")

            # Check keys in networking dict
            # Check key is str, and properly formatted, this should be suffix to urls. "default" means no suffix.
            for env_key, env_val in v.items():
                if not isinstance(env_key, str):
                    raise TypeError(f"networking key must be str. Got type {type(env_key).__name__}.")
                res = re.fullmatch(r'[a-z0-9]+', env_key)
                if not res:
                    raise ValueError(f"networking key must be lowercase alphanumeric. Default is 'default'.")
                if len(env_key) > 64 or len(env_key) < 3:
                    raise ValueError(f"networking key length must be between 3-64 characters. Inputted length: {len(env_key)}")
        return v

    @validator('compute_queue')
    def check_compute_queue(cls, v):
        if v:
            # Ensure compute queue alphanumeric.
            res = re.fullmatch(r'[a-z0-9]+', v)
            if not res:
                raise ValueError(f"compute_queue must be lowercase alphanumeric.")

            ### Check if the queue exists in config, database later
            deducted_queue = get_queue_by_name(conf.compute_queues, v)
            if not deducted_queue:
                raise ValueError(f"compute_queue must be in compute_queues list in cluster configuration.")
        return v

    @model_validator(mode="after")
    def set_k8_name_and_networking_urls(cls, values):
        # NOTE: Pydantic loops during validation, so for a few calls, tenant_id and site_id will be NONE.
        # Must account for this. By end of loop, everything will be set properly.
        # In this case "tacc" tenant is backup.
        site_id = getattr(values, 'site_id', None)
        tenant_id = getattr(values, 'tenant_id', 'tacc')
        pod_id = getattr(values, 'pod_id', None)
        ### k8_name: pods-<site>-<tenant>-<pod_id>
        #values.k8_name = f"pods-{site_id}-{tenant_id}-{pod_id}"
        object.__setattr__(values, "k8_name", f"pods-{site_id}-{tenant_id}-{pod_id}")
        ### url: podname-networking_name.pods.tacc.develop.tapis.io
        # base_url in the form of https://tacc.develop.tapis.io.
        logger.debug("Fetching base_url for k8_name Pod model_validator from tenant_cache")
        if not tenant_id or not site_id:
            logger.debug("tenant_id or site_id is None, returning values")
            return values
        logger.debug(f"tenant_id: {tenant_id}, site_id: {site_id}")
        base_url = t.tenant_cache.get_tenant_config(tenant_id=tenant_id).base_url

        # Ensure the object already exists, this function loops a lot before value is set.
        if getattr(values, 'networking'):
            for net_name, net_info in values.networking.items():
                # The Networking model needs to be transformed to a dict if it's being used. When we get with alchemy
                # the entire object is already a dict though. So we always expect a dict.
                if not isinstance(net_info, dict):
                    net_info = net_info.dict()

                # if networking.name is specified we add it to the pod_name of our url after a hyphen. 'default' does not do this.
                # i.e. "podname-networkname" instead of just "podname" when networking.name == 'default'
                if net_name == 'default':
                    url = base_url.replace("https://", f"{pod_id}.pods.")
                else:
                    url = base_url.replace("https://", f"{pod_id}-{net_name}.pods.")
                # Set 'url' in networking dict.
                try:
                    object.__setattr__(values.networking[net_name], 'url', url)
                except AttributeError:
                    pass
        return values

    def display(self, include_configs: bool = False):
        display = self.dict()
        display.pop('logs', None)
        display.pop('k8_name')
        display.pop('tenant_id')
        display.pop('permissions')
        display.pop('site_id')
        display.pop('modified_fields')
        display.pop('action_logs', None)
        #display['action_logs'] = display['action_logs'][-10:]
        
        # Redact config_content if not requested
        if not include_configs and display.get('volume_mounts'):
            for mount_path, mount_config in display['volume_mounts'].items():
                if mount_config and isinstance(mount_config, dict) and mount_config.get('type') == 'ephemeral' and mount_config.get('config_content'):
                    content_size = len(mount_config['config_content'])
                    mount_config['config_content'] = f"<{content_size} bytes - use ?include_configs=true to retrieve>"
        
        return display

    def get_pod_definition_for_template_tag(self):
        template_tag_bit = self.dict()
        template_tag_bit.pop('pod_id')
        template_tag_bit.pop('tenant_id')
        template_tag_bit.pop('site_id')
        template_tag_bit.pop('k8_name')
        template_tag_bit.pop('logs', None)
        template_tag_bit.pop('permissions')
        template_tag_bit.pop('action_logs')
        template_tag_bit.pop('status_requested')
        template_tag_bit.pop('status_container')
        template_tag_bit.pop('status')
        template_tag_bit.pop('update_ts')
        template_tag_bit.pop('time_to_stop_ts')
        template_tag_bit.pop('start_instance_ts')
        template_tag_bit.pop('creation_ts')
        modified_fields = template_tag_bit.pop('modified_fields')

        return template_tag_bit, modified_fields

    @classmethod
    def db_get_all_with_permission(cls, user, level, tenant, site, defer_columns: list = None):
        """
        Get all and ensure permission exists.
        Defers logs and action_logs columns by default to reduce data transfer.
        """
        if defer_columns is None:
            defer_columns = [cls.logs, cls.action_logs]

        site, tenant, store = cls.get_site_tenant_session(tenant=tenant, site=site)
        table_name = cls.table_name()
        logger.info(f'Top of {table_name}.db_get_all_with_permissions() for tenant.site: {tenant}.{site}')

        # Get list of level specified + levels above.
        authorized_levels = PermissionLevel(level).authorized_levels()

        # Create list of permissions user needs to access this resource
        # In the case of level=USER, USER and ADMIN work, so: ["cgarcia:ADMIN", "cgarcia:USER"]
        permission_list = []
        for authed_level in authorized_levels:
            permission_list.append(f"{user}:{authed_level}")

        # Create statement
        stmt = select(Pod).where(Pod.permissions.overlap(permission_list))
        if defer_columns:
            stmt = stmt.options(*[defer(col) for col in defer_columns])

        # Run command
        results = store.run("execute", stmt, scalars=True, all=True)

        logger.info(f"Got rows from table {tenant}.{table_name}.")
        return results


class NewPod(PodBase):
    """
    Object with fields that users are allowed to specify for the Pod class.
    """
    pass


class UpdatePod(TapisApiModel):
    """
    Object with fields that users are allowed to specify for the Pod class.
    """
    # Optional
    image: str = Field("", description = "Which docker image to use, must be on allowlist, check /pods/images for list.")
    template: str = Field("", description = "Which pod template to use as base of pod fields. User set attributes will overwrite template fields.")
    description: Optional[str] = Field("", description = "Description of this pod.")
    command: Optional[List[str]] = Field(None, description = 'Command to run in pod. ex. ["sleep", "5000"] or ["/bin/bash", "-c", "(exec myscript.sh)"]', sa_column=Column(ARRAY(String)))
    arguments: List[str] | None = Field(None, description = "Arguments for the Pod's command.", sa_column=Column(ARRAY(String)))
    environment_variables: Optional[Dict[str, Any]] = Field({}, description = "Environment variables to inject into k8 pod. Use `${pods:secrets:KEY}` to reference secret_map entries.", sa_column=Column(JSON))
    secret_map: Optional[Dict[str, str]] = Field(None, description = "Map of keys to secret values. Syntax: ${secret:name} (user secret), ${secret:user:name} (explicit owner). Reference in environment_variables via ${pods:secrets:KEY}. Resolved at pod start.", sa_column=Column(JSON))
    status_requested: Optional[str] = Field("ON", description = "Status requested by user, `ON`, `OFF`, or `RESTART`.")
    volume_mounts: Optional[Dict[str, Optional[VolumeMount]]] = Field(
        {}, 
        description = 'Volume mounts keyed by mount_path. Values are VolumeMount objects (see schema) or null (to remove inherited mount). Ex: {"/data": {"type": "tapisvolume", "source_id": "myvolume"}, "/etc/config.ini": {"type": "ephemeral", "config_content": "key=value"}}',
        sa_column=Column(JSON)
    )
    time_to_stop_default: Optional[int] = Field(43200, description = "Default time (sec) for pod to run from instance start. -1 for unlimited. 12 hour default.")
    time_to_stop_instance: Optional[int] = Field(None, description = "Time (sec) for pod to run from instance start. Reset each time instance is started. -1 for unlimited. None uses default.")
    networking: Optional[Dict[str, Networking]] = Field({"default": {"protocol": "http", "port": 5000}}, description = 'Networking information. {"url_suffix": {"protocol": "http"  "tcp", "port": int}}', sa_column=Column(JSON))
    resources: Optional[Resources] = Field({}, description = 'Pod resource management {"cpu_limit": 3000, "mem_limit": 3000, "cpu_request": 500, "mem_limit": 500, "gpu": 0}', sa_column=Column(JSON))
    compute_queue: str = Field("default", description = "Queue to run pod in. `default` is the default queue.")
    template_overrides: Optional[Dict[str, Any]] = Field(None, description = 'Partial overrides for template values. Override volume_mounts or secret_map values without rewriting full template field. Ex: {"volume_mounts": {"/data": {"source_id": "my-vol"}}, "secret_map": {"DB_PASS": "${secret:mypass}"}}', sa_column=Column(JSON))

    
class ExecutePodCommands(BaseModel):
    commands: Union[List[str], List[List[str]]] = Field(..., description = "List of commands to run in pod. ex. `['sleep 5000', 'ls -l']` or `[['sleep', '5000'], ['ls', '-l']]")
    total_timeout: Optional[int] = Field(300, description = "Total time (sec) to wait for all commands to finish. Default 300 seconds.")
    command_timeout: Optional[int] = Field(60, description = "Time (sec) to wait for each command to finish. Default 60 seconds.")
    fail_on_non_success: Optional[bool] = Field(True, description = "If True, will fail if any command does not return 0. Default True.")


class PodResponseModel(PodBaseRead):
    """
    Response object for Pod class.
    """
    pass


class PodResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: PodResponseModel
    status: str
    version: str


class PodsResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: List[PodResponseModel]
    status: str
    version: str


class PodsFinalResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: Dict
    status: str
    version: str

class PodDeleteResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: str
    status: str
    version: str


class PodPermissionsResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: PermissionsModel
    status: str
    version: str


class PodLogsResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: LogsModel
    status: str
    version: str


class PodCredentialsResponse(TapisApiModel):
    message: str
    metadata: Dict
    result: CredentialsModel
    status: str
    version: str
