"""init22

Revision ID: 1c92361d84cc
Revises: d7c3e9a14f08
Create Date: 2026-06-09 01:07:16.100297

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = '1c92361d84cc'
down_revision = 'd7c3e9a14f08'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pod', 'stack_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('pod', 'ready_condition',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('pod', 'force_stop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('stack', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stack', 'restart_policy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stack', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stack', 'from_template',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('stack', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stack', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stack', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templatetag', 'kind',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pod'::character varying"))
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templatetag', 'kind',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pod'::character varying"))
    op.alter_column('stack', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stack', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stack', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stack', 'from_template',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('stack', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stack', 'restart_policy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stack', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'force_stop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pod', 'ready_condition',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('pod', 'stack_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
