"""init10

Revision ID: 2be2a0f5c642
Revises: d3006d3ab8d5
Create Date: 2025-05-18 04:20:21.486479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = '2be2a0f5c642'
down_revision = 'd3006d3ab8d5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'admin_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'admin_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'user_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('pod', 'template',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('pod', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'status_requested',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'time_to_stop_default',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pod', 'compute_queue',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('pod', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pod', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'destination_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'size_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('snapshot', 'cron',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'retention_policy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('snapshot', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshot', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('template', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('template', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('template', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templatetag', 'commit_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templatetag', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templatetag', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'size_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('volume', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('volume', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volume', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volume', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volume', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volume', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volume', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volume', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volume', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volume', 'size_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volume', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('templatetag', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('templatetag', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('templatetag', 'commit_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('template', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('template', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('template', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('snapshot', 'retention_policy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'cron',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'size_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('snapshot', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshot', 'destination_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'logs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'k8_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'compute_queue',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('pod', 'time_to_stop_default',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pod', 'status_requested',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pod', 'template',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('pod', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('password', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('password', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('password', 'user_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('password', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('password', 'admin_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('password', 'admin_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
