"""init12

Revision ID: 5162ee088365
Revises: a1975c45c014
Create Date: 2025-12-17 06:32:17.836724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = '5162ee088365'
down_revision = 'a1975c45c014'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('readable', sa.Boolean(), nullable=False))
    op.add_column('secret', sa.Column('writable', sa.Boolean(), nullable=False))
    op.drop_column('secret', 'read_write')
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('read_write', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('secret', 'writable')
    op.drop_column('secret', 'readable')
    # ### end Alembic commands ###
