"""init2

Revision ID: 62000d2afe49
Revises: a67403ad010a
Create Date: 2022-09-27 15:58:36.746967

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62000d2afe49'
down_revision = 'a67403ad010a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exporteddata')
    op.add_column('pod', sa.Column('persistent_volume', sa.BOOLEAN(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod', 'persistent_volume')
    op.create_table('exporteddata',
    sa.Column('source_pod', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('roles_required', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creation_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('roles_inherited', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('export_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_pod', name='exporteddata_pkey')
    )
    # ### end Alembic commands ###
