"""init16

Revision ID: 89eebaf0ea78
Revises: b4c7d8e9f0a1
Create Date: 2026-02-12 01:17:17.866246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = '89eebaf0ea78'
down_revision = 'b4c7d8e9f0a1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templatetag', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('templatetag', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templatetag', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('templatetag', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
