"""init

Revision ID: 8d2f17bb9a83
Revises: 
Create Date: 2022-05-02 19:39:49.254834

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = '8d2f17bb9a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_tacc_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_dev():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_dev():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_tacc():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_tacc():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_cii():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_cii():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_a2cps():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_a2cps():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_githubHYPHENdemo():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_githubHYPHENdemo():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_tacc_icicle():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_tacc_icicle():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_uh_uhdev():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_uh_uhdev():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###


def upgrade_uh_uhadmin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exporteddata',
    sa.Column('source_pod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('source_pod')
    )
    op.create_table('password',
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    op.create_table('pod',
    sa.Column('container_status', sa.JSON(), nullable=True),
    sa.Column('pod_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k8_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_attached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roles_inherited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('pod_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade_uh_uhadmin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    op.drop_table('password')
    op.drop_table('exporteddata')
    # ### end Alembic commands ###

