"""cluster table + pod.healthchecks JSONB->JSON (post-init21)

Revision ID: a014bbaf8ee8
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 18:28:40.024825

NOTE: the original autogenerated version of this migration also dropped
traffic_logs, pod_log_runs, and templategallery (an autogenerate artifact
from a dev database that predated init17-init19) — destroying their data on
any schema that upgraded through it (recovered on develop by init24's
checkfirst re-create). The drops are removed here so the chain never
destroys those tables; environments that already ran the bad version are
past this revision and unaffected.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a014bbaf8ee8'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    op.create_table('cluster',
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('k8config', sa.JSON(), nullable=True),
    sa.Column('k8username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('db_secret_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rabbit_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rabbit_vhost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rabbit_secret_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vector_writer_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts_preauthkey_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts_preauthkey_expires', sa.DateTime(), nullable=True),
    sa.Column('ts_routes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ts_stats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_bootstrap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_bootstrap_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('action_logs', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.alter_column('pod', 'healthchecks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)


def downgrade_alltenants():
    op.alter_column('pod', 'healthchecks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('cluster')
