"""init11

Revision ID: a1975c45c014
Revises: 2be2a0f5c642
Create Date: 2025-12-09 22:01:45.671446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1975c45c014'
down_revision = '2be2a0f5c642'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'id')
    )
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=True)
    op.create_index(op.f('ix_log_log_type'), 'log', ['log_type'], unique=False)
    op.create_index(op.f('ix_log_resource_id'), 'log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_log_resource_type'), 'log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_log_tenant_id'), 'log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_log_time'), 'log', ['time'], unique=False)
    op.create_index(op.f('ix_log_username'), 'log', ['username'], unique=False)
    op.create_table('secret',
    sa.Column('secret_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pod_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_write', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sk_secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_ts', sa.DateTime(), nullable=True),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.PrimaryKeyConstraint('secret_id')
    )
    op.add_column('pod', sa.Column('secret_map', sa.JSON(), nullable=True, server_default='{}'))
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template', 'archive_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('pod', 'secret_map')
    op.drop_table('secret')
    op.drop_index(op.f('ix_log_username'), table_name='log')
    op.drop_index(op.f('ix_log_time'), table_name='log')
    op.drop_index(op.f('ix_log_tenant_id'), table_name='log')
    op.drop_index(op.f('ix_log_resource_type'), table_name='log')
    op.drop_index(op.f('ix_log_resource_id'), table_name='log')
    op.drop_index(op.f('ix_log_log_type'), table_name='log')
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
