"""init24 — recreate traffic_logs, pod_log_runs, templategallery

These three tables were erroneously dropped by migration a014bbaf8ee8 (init16),
which was autogenerated while alembic/env.py was missing the model imports for
models_traffic, models_pod_log_runs, and models_template_gallery. With those
models absent from target_metadata, autogenerate diffed the live tables as
"present in DB but not in metadata" and emitted drop_table for each. env.py has
since been fixed; this migration restores the tables on any DB already migrated
past a014bbaf8ee8.

Idempotent: tables are created via the current model metadata with checkfirst=True,
so this is a no-op on schemas where the tables already exist.

Revision ID: b7d4e1f9a2c3
Revises: 1c92361d84cc
Create Date: 2026-06-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy

from models_traffic import TrafficLog
from models_pod_log_runs import PodLogRun
from models_template_gallery import TemplateGallery

# revision identifiers, used by Alembic.
revision = 'b7d4e1f9a2c3'
down_revision = '1c92361d84cc'
branch_labels = None
depends_on = None

# Tables erroneously dropped by a014bbaf8ee8, recreated here.
_TABLES = (TrafficLog, PodLogRun, TemplateGallery)


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()


def upgrade_alltenants():
    bind = op.get_bind()
    for model in _TABLES:
        # checkfirst=True -> idempotent CREATE TABLE/INDEX IF NOT EXISTS in the
        # current tenant schema (search_path is set per-tenant by env.py).
        model.__table__.create(bind=bind, checkfirst=True)


def downgrade_alltenants():
    bind = op.get_bind()
    for model in reversed(_TABLES):
        model.__table__.drop(bind=bind, checkfirst=True)
