"""init4

Revision ID: e9df9a15e8e1
Revises: 1249c846b8f9
Create Date: 2022-10-29 18:33:57.457910

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e9df9a15e8e1'
down_revision = '1249c846b8f9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('resources', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default=sa.text("'{}'::json")))
    op.add_column('pod', sa.Column('command', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('pod', sa.Column('networking', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default=sa.text("'{}'::json")))
    op.drop_column('pod', 'routing_port')
    op.drop_column('pod', 'server_protocol')
    op.drop_column('pod', 'url')
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pod', sa.Column('routing_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pod', sa.Column('server_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('pod', 'resources')
    op.drop_column('pod', 'networking')
    op.drop_column('pod', 'command')
    # ### end Alembic commands ###
