"""init14

Revision ID: ecbca391a887
Revises: f8a9b3c2d1e0
Create Date: 2026-01-05 17:36:27.814694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ecbca391a887'
down_revision = 'f8a9b3c2d1e0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templatetag', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=''))
    op.add_column('templatetag', sa.Column('archive_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=''))
    op.add_column('templatetag', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("current_schema()")))
    op.add_column('templatetag', sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("current_database()")))
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templatetag', 'site_id')
    op.drop_column('templatetag', 'tenant_id')
    op.drop_column('templatetag', 'archive_message')
    op.drop_column('templatetag', 'description')
    # ### end Alembic commands ###
