"""init3

Revision ID: f17e942e4e0a
Revises: 62000d2afe49
Create Date: 2022-10-04 17:51:06.146948

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy


# revision identifiers, used by Alembic.
revision = 'f17e942e4e0a'
down_revision = '62000d2afe49'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('time_to_run', sa.Integer(), nullable=True, server_default=str(-1)))
    op.add_column('pod', sa.Column('start_ts', sa.DateTime(), nullable=True))
    op.drop_column('pod', 'persistent_volume')
    op.add_column('pod', sa.Column('persistent_volume', sa.JSON(), nullable=False, server_default=str({})))
    # ### end Alembic commands ###


def downgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod', 'persistent_volume')
    op.add_column('pod', sa.Column('persistent_volume', sa.BOOLEAN(), nullable=False, server_default=str(False)))
    op.drop_column('pod', 'start_ts')
    op.drop_column('pod', 'time_to_run')
    # ### end Alembic commands ###
