import sys
sys.path.append('/home/tapis/service')

import logging
from logging.config import fileConfig
import re
import os
import hashlib

from sqlalchemy import create_engine, text
from sqlalchemy import pool


def _advisory_key(name: str) -> int:
    """Stable signed-bigint key for a Postgres advisory lock, derived from a schema name.
    Used to serialize concurrent `alembic upgrade` runs (multiple API replicas start at once)
    so they don't race on the same tenant schema."""
    h = hashlib.sha1(("pods_alembic:" + name).encode()).digest()
    # 63-bit unsigned, shifted into the signed bigint range pg_advisory_xact_lock expects.
    return int.from_bytes(h[:8], "big") % (2 ** 63) - (2 ** 62)

from alembic import context

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
fileConfig(config.config_file_name)
logger = logging.getLogger("alembic.env")


### Service Changes. We pull info from the main code. Like sites and tenants so we can add that data to the alembic.ini file.
from tapisservice.config import conf
from sqlmodel import create_engine, Session, select, SQLModel
from stores import pg_store, pg_default

# Get config settings to create conninfo later
username = conf.postgres_user
password = conf.postgres_pass
host = conf.postgres_host

engines = {}
all_urls = {}
# Create databases and schemas wanted.
for site, tenants in pg_store.items():
    # Create database and fail gracefully if it already exists
    try:
        pg_default.run('execute', text(f'CREATE DATABASE "{site}"'), autocommit=True)
    except Exception as e:
        msg = f"Database for site: {site}, already exists. Skipping. Error: {repr(e)}"
        logger.warning(msg)
    
    # Create schemas for each tenant
    for tenant, pg in tenants.items():
        try:
            # TODO indexes! #CREATE CONSTRAINT FOR (p:Pod) REQUIRE p.name IS UNIQUE
            pg.run("execute", text(f'CREATE SCHEMA IF NOT EXISTS "{tenant}"'), autocommit=True)
        except Exception as e:
            msg = f"Error when creating schemas for tenant: {tenant}. e: {repr(e)}"
            logger.warning(msg)

        # Add database connection info to alembic config
        conninfo = f"postgresql://{username}:{password}@{host}/{site}"#?options=-csearch_path%3Ddbo,{tenant}"
        name = f"{site}_{tenant}".replace("-", "HYPHEN") # Some tenants have - in their names. This messes up alembic later.
        all_urls[site] = conninfo
        engines[name] = create_engine(conninfo)
        config.set_section_option(name, "sqlalchemy.url", conninfo)

# Add databases to alembic's list of databases.
config.set_main_option("databases", ",".join(all_urls.keys()))

# gather section names referring to databases.
db_names = config.get_main_option("databases")
logger.warning(f"Using the following databases with alembic: {db_names}")

######### Import all of the models we want to be autogenerated. Will proliferate to all schemas.
from models_pods import Pod, Password
from models_volumes import Volume
from models_snapshots import Snapshot
from models_templates import Template
from models_images import Image
from models_templates_tags import TemplateTag
from models_cluster import Cluster
from models_logs import Log
from models_secrets import Secret
from models_stacks import Stack
from models_traffic import TrafficLog
from models_pod_log_runs import PodLogRun
from models_template_gallery import TemplateGallery

target_metadata = SQLModel.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_example_option = config.get_main_option("my_example_option")

def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    # This callback is used to prevent an auto-migration from being generated when
    # there are no changes to the schema https://stackoverflow.com/questions/70203927
    def process_revision_directives(context, revision, directives):
        # `autogenerate` is only present on cmd_opts for `alembic revision`;
        # it's absent for `alembic check`, so guard with getattr.
        if getattr(config.cmd_opts, "autogenerate", False):
            script = directives[0]
            if not script.upgrade_ops_list and script.upgrade_ops.is_empty():
                directives[:] = []
                print('No changes in schema detected.')

    # Create transactions/connections here so we can rollback/close later.
    connections = []
    transactions = []
    logger.info(f"engine: {engines}")

    try:
        # Create tables in each tenant(schema) in each database.
        for name, engine in engines.items():
            site, tenant = name.split('_')
            tenant = tenant.replace('HYPHEN', '-')

            ## GO THROUGH ALL TENANTS, MEANING MIGRATE TO EACH SCHEMA!
            logger.info(f"Migrating database {site}; tenant {tenant}")
            # Reference https://alembic.sqlalchemy.org/en/latest/cookbook.html#rudimental-schema-level-multi-tenancy-for-postgresql-databases
            # Get engine/connection/transaction and add some schema stuff to it.
            logger.info(f"{engine}")
            with engine.connect() as connection:
                logger.info(f"{connection}")
                # Start a transaction context
                with connection.begin():
                    # Serialize concurrent migrators: multiple API replicas all run
                    # `alembic upgrade head` on startup, and racing on the same tenant schema
                    # caused intermittent failures (the "restart it twice" symptom). A
                    # transaction-scoped advisory lock makes the others wait, then find the
                    # schema already at head (no-op). pg_advisory_xact_lock auto-releases at
                    # COMMIT/ROLLBACK — no manual unlock, safe across crashes.
                    connection.execute(
                        text("SELECT pg_advisory_xact_lock(:k)"),
                        {"k": _advisory_key(name)},
                    )
                    connection.execute(text(f'SET search_path TO "{tenant}"'))
                    connection.dialect.default_schema_name = tenant
                    context.configure(
                        connection=connection,
                        include_schemas=False,
                        upgrade_token=f"upgrade_alltenants",
                        downgrade_token=f"downgrade_alltenants",
                        target_metadata=target_metadata,
                        process_revision_directives=process_revision_directives
                    )
                    context.run_migrations(engine_name=name)
    except Exception:
        logger.exception("Migration failed")
        raise
    logger.debug("==========================================")
    logger.debug("Migration completed successfully")

    # try:
    #     # Create tables in each tenant(schema) in each database.
    #     for name, engine in engines.items():
    #         site, tenant = name.split('_')
    #         tenant = tenant.replace('HYPHEN', '-')

    #         ## GO THROUGH ALL TENANTS, MEANING MIGRATE TO EACH SCHEMA!
    #         logger.info(f"Migrating database {site}; tenant {tenant}")
    #         # Reference https://alembic.sqlalchemy.org/en/latest/cookbook.html#rudimental-schema-level-multi-tenancy-for-postgresql-databases
    #         # Get engine/connection/transaction and add some schema stuff to it.
    #         logger.info(f"{engine}")
    #         connection = engine.connect()
    #         logger.info(f"{connection}")
    #         # Use text() for SQL expressions
    #         connection.execute(text(f'set search_path to "{tenant}"'))
    #         connection.dialect.default_schema_name = tenant
    #         connections.append(connection)
    #         # Create transaction
    #         transaction = connection.begin()
    #         transactions.append(transaction)
    #         # Create context
    #         context.configure(
    #             connection=connection,
    #             include_schemas=False, # Has to be False else migrations will be made per schema, when we want it done for all.
    #             upgrade_token=f"upgrade_alltenants",
    #             downgrade_token=f"downgrade_alltenants",
    #             target_metadata=target_metadata,
    #             process_revision_directives=process_revision_directives
    #         )
    #         context.run_migrations(engine_name=name)

    #     for transaction in transactions:
    #         transaction.commit()
    # except:
    #     for transaction in transactions:
    #         transaction.rollback()
    #     raise
    # finally:
    #     for connection in connections:
    #         connection.close()


run_migrations_online()
